package com.creditease.adx.clockwork.dao.mapper.clockwork;

import com.creditease.adx.clockwork.common.entity.gen.TbClockworkDag;
import com.creditease.adx.clockwork.common.entity.gen.TbClockworkDagExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TbClockworkDagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_dag
     *
     * @mbg.generated Tue Aug 04 15:44:30 CST 2020
     */
    long countByExample(TbClockworkDagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_dag
     *
     * @mbg.generated Tue Aug 04 15:44:30 CST 2020
     */
    int deleteByExample(TbClockworkDagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_dag
     *
     * @mbg.generated Tue Aug 04 15:44:30 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_dag
     *
     * @mbg.generated Tue Aug 04 15:44:30 CST 2020
     */
    int insert(TbClockworkDag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_dag
     *
     * @mbg.generated Tue Aug 04 15:44:30 CST 2020
     */
    int insertSelective(TbClockworkDag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_dag
     *
     * @mbg.generated Tue Aug 04 15:44:30 CST 2020
     */
    List<TbClockworkDag> selectByExample(TbClockworkDagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_dag
     *
     * @mbg.generated Tue Aug 04 15:44:30 CST 2020
     */
    TbClockworkDag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_dag
     *
     * @mbg.generated Tue Aug 04 15:44:30 CST 2020
     */
    int updateByExampleSelective(@Param("record") TbClockworkDag record, @Param("example") TbClockworkDagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_dag
     *
     * @mbg.generated Tue Aug 04 15:44:30 CST 2020
     */
    int updateByExample(@Param("record") TbClockworkDag record, @Param("example") TbClockworkDagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_dag
     *
     * @mbg.generated Tue Aug 04 15:44:30 CST 2020
     */
    int updateByPrimaryKeySelective(TbClockworkDag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_dag
     *
     * @mbg.generated Tue Aug 04 15:44:30 CST 2020
     */
    int updateByPrimaryKey(TbClockworkDag record);
}