/**
 * This file is automatically generated by MyBatis Generator, do not modify.
 */
package com.creditease.adx.clockwork.dao.mapper.clockwork;

import com.creditease.adx.clockwork.common.entity.gen.TbClockworkUser;
import com.creditease.adx.clockwork.common.entity.gen.TbClockworkUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbClockworkUserMapper {
    long countByExample(TbClockworkUserExample example);

    int deleteByExample(TbClockworkUserExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(TbClockworkUser record);

    int insertSelective(TbClockworkUser record);

    List<TbClockworkUser> selectByExample(TbClockworkUserExample example);

    TbClockworkUser selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") TbClockworkUser record, @Param("example") TbClockworkUserExample example);

    int updateByExample(@Param("record") TbClockworkUser record, @Param("example") TbClockworkUserExample example);

    int updateByPrimaryKeySelective(TbClockworkUser record);

    int updateByPrimaryKey(TbClockworkUser record);

    int batchInsert(List<TbClockworkUser> records);
}