/**
 * This file is automatically generated by MyBatis Generator, do not modify.
 */
package com.creditease.adx.clockwork.dao.mapper.clockwork;

import com.creditease.adx.clockwork.common.entity.gen.TbClockworkUserRole;
import com.creditease.adx.clockwork.common.entity.gen.TbClockworkUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbClockworkUserRoleMapper {
    long countByExample(TbClockworkUserRoleExample example);

    int deleteByExample(TbClockworkUserRoleExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(TbClockworkUserRole record);

    int insertSelective(TbClockworkUserRole record);

    List<TbClockworkUserRole> selectByExample(TbClockworkUserRoleExample example);

    TbClockworkUserRole selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") TbClockworkUserRole record, @Param("example") TbClockworkUserRoleExample example);

    int updateByExample(@Param("record") TbClockworkUserRole record, @Param("example") TbClockworkUserRoleExample example);

    int updateByPrimaryKeySelective(TbClockworkUserRole record);

    int updateByPrimaryKey(TbClockworkUserRole record);
}