/**
 * This file is automatically generated by MyBatis Generator, do not modify.
 */
package com.creditease.adx.clockwork.dao.mapper.clockwork;

import com.creditease.adx.clockwork.common.entity.gen.TbClockworkTask;
import com.creditease.adx.clockwork.common.entity.gen.TbClockworkTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbClockworkTaskMapper {
    long countByExample(TbClockworkTaskExample example);

    int deleteByExample(TbClockworkTaskExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(TbClockworkTask record);

    int insertSelective(TbClockworkTask record);

    List<TbClockworkTask> selectByExample(TbClockworkTaskExample example);

    TbClockworkTask selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") TbClockworkTask record, @Param("example") TbClockworkTaskExample example);

    int updateByExample(@Param("record") TbClockworkTask record, @Param("example") TbClockworkTaskExample example);

    int updateByPrimaryKeySelective(TbClockworkTask record);

    int updateByPrimaryKey(TbClockworkTask record);

    int batchInsert(List<TbClockworkTask> records);
}