/**
 * This file is automatically generated by MyBatis Generator, do not modify.
 */
package com.creditease.adx.clockwork.dao.mapper.clockwork;

import com.creditease.adx.clockwork.common.entity.gen.TbClockworkTaskRerun;
import com.creditease.adx.clockwork.common.entity.gen.TbClockworkTaskRerunExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbClockworkTaskRerunMapper {
    long countByExample(TbClockworkTaskRerunExample example);

    int deleteByExample(TbClockworkTaskRerunExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(TbClockworkTaskRerun record);

    int insertSelective(TbClockworkTaskRerun record);

    List<TbClockworkTaskRerun> selectByExampleWithBLOBs(TbClockworkTaskRerunExample example);

    List<TbClockworkTaskRerun> selectByExample(TbClockworkTaskRerunExample example);

    TbClockworkTaskRerun selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") TbClockworkTaskRerun record, @Param("example") TbClockworkTaskRerunExample example);

    int updateByExampleWithBLOBs(@Param("record") TbClockworkTaskRerun record, @Param("example") TbClockworkTaskRerunExample example);

    int updateByExample(@Param("record") TbClockworkTaskRerun record, @Param("example") TbClockworkTaskRerunExample example);

    int updateByPrimaryKeySelective(TbClockworkTaskRerun record);

    int updateByPrimaryKeyWithBLOBs(TbClockworkTaskRerun record);

    int updateByPrimaryKey(TbClockworkTaskRerun record);

    int batchInsert(List<TbClockworkTaskRerun> records);
}