/**
 * This file is automatically generated by MyBatis Generator, do not modify.
 */
package com.creditease.adx.clockwork.dao.mapper.clockwork;

import com.creditease.adx.clockwork.common.entity.gen.TbClockworkTaskLog;
import com.creditease.adx.clockwork.common.entity.gen.TbClockworkTaskLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbClockworkTaskLogMapper {
    long countByExample(TbClockworkTaskLogExample example);

    int deleteByExample(TbClockworkTaskLogExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(TbClockworkTaskLog record);

    int insertSelective(TbClockworkTaskLog record);

    List<TbClockworkTaskLog> selectByExample(TbClockworkTaskLogExample example);

    TbClockworkTaskLog selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") TbClockworkTaskLog record, @Param("example") TbClockworkTaskLogExample example);

    int updateByExample(@Param("record") TbClockworkTaskLog record, @Param("example") TbClockworkTaskLogExample example);

    int updateByPrimaryKeySelective(TbClockworkTaskLog record);

    int updateByPrimaryKey(TbClockworkTaskLog record);

    int batchInsert(List<TbClockworkTaskLog> records);
}