/**
 * This file is automatically generated by MyBatis Generator, do not modify.
 */
package com.creditease.adx.clockwork.dao.mapper.clockwork;

import com.creditease.adx.clockwork.common.entity.gen.TbClockworkTaskSubscription;
import com.creditease.adx.clockwork.common.entity.gen.TbClockworkTaskSubscriptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbClockworkTaskSubscriptionMapper {
    long countByExample(TbClockworkTaskSubscriptionExample example);

    int deleteByExample(TbClockworkTaskSubscriptionExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(TbClockworkTaskSubscription record);

    int insertSelective(TbClockworkTaskSubscription record);

    List<TbClockworkTaskSubscription> selectByExample(TbClockworkTaskSubscriptionExample example);

    TbClockworkTaskSubscription selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") TbClockworkTaskSubscription record, @Param("example") TbClockworkTaskSubscriptionExample example);

    int updateByExample(@Param("record") TbClockworkTaskSubscription record, @Param("example") TbClockworkTaskSubscriptionExample example);

    int updateByPrimaryKeySelective(TbClockworkTaskSubscription record);

    int updateByPrimaryKey(TbClockworkTaskSubscription record);

    int batchInsert(List<TbClockworkTaskSubscription> records);
}