package com.creditease.adx.clockwork.dao.mapper.clockwork;

import com.creditease.adx.clockwork.common.entity.gen.TbClockworkTaskFillDataTimeQueue;
import com.creditease.adx.clockwork.common.entity.gen.TbClockworkTaskFillDataTimeQueueExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TbClockworkTaskFillDataTimeQueueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_task_fill_data_time_queue
     *
     * @mbg.generated Tue Aug 04 15:51:46 CST 2020
     */
    long countByExample(TbClockworkTaskFillDataTimeQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_task_fill_data_time_queue
     *
     * @mbg.generated Tue Aug 04 15:51:46 CST 2020
     */
    int deleteByExample(TbClockworkTaskFillDataTimeQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_task_fill_data_time_queue
     *
     * @mbg.generated Tue Aug 04 15:51:46 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_task_fill_data_time_queue
     *
     * @mbg.generated Tue Aug 04 15:51:46 CST 2020
     */
    int insert(TbClockworkTaskFillDataTimeQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_task_fill_data_time_queue
     *
     * @mbg.generated Tue Aug 04 15:51:46 CST 2020
     */
    int insertSelective(TbClockworkTaskFillDataTimeQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_task_fill_data_time_queue
     *
     * @mbg.generated Tue Aug 04 15:51:46 CST 2020
     */
    List<TbClockworkTaskFillDataTimeQueue> selectByExample(TbClockworkTaskFillDataTimeQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_task_fill_data_time_queue
     *
     * @mbg.generated Tue Aug 04 15:51:46 CST 2020
     */
    TbClockworkTaskFillDataTimeQueue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_task_fill_data_time_queue
     *
     * @mbg.generated Tue Aug 04 15:51:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") TbClockworkTaskFillDataTimeQueue record, @Param("example") TbClockworkTaskFillDataTimeQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_task_fill_data_time_queue
     *
     * @mbg.generated Tue Aug 04 15:51:46 CST 2020
     */
    int updateByExample(@Param("record") TbClockworkTaskFillDataTimeQueue record, @Param("example") TbClockworkTaskFillDataTimeQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_task_fill_data_time_queue
     *
     * @mbg.generated Tue Aug 04 15:51:46 CST 2020
     */
    int updateByPrimaryKeySelective(TbClockworkTaskFillDataTimeQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_task_fill_data_time_queue
     *
     * @mbg.generated Tue Aug 04 15:51:46 CST 2020
     */
    int updateByPrimaryKey(TbClockworkTaskFillDataTimeQueue record);
}