package com.creditease.adx.clockwork.dao.mapper.clockwork;

import com.creditease.adx.clockwork.common.entity.gen.TbClockworkTaskAndSlotRelation;
import com.creditease.adx.clockwork.common.entity.gen.TbClockworkTaskAndSlotRelationExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TbClockworkTaskAndSlotRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_task_and_slot_relation
     *
     * @mbg.generated Wed Aug 05 09:46:16 CST 2020
     */
    long countByExample(TbClockworkTaskAndSlotRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_task_and_slot_relation
     *
     * @mbg.generated Wed Aug 05 09:46:16 CST 2020
     */
    int deleteByExample(TbClockworkTaskAndSlotRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_task_and_slot_relation
     *
     * @mbg.generated Wed Aug 05 09:46:16 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_task_and_slot_relation
     *
     * @mbg.generated Wed Aug 05 09:46:16 CST 2020
     */
    int insert(TbClockworkTaskAndSlotRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_task_and_slot_relation
     *
     * @mbg.generated Wed Aug 05 09:46:16 CST 2020
     */
    int insertSelective(TbClockworkTaskAndSlotRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_task_and_slot_relation
     *
     * @mbg.generated Wed Aug 05 09:46:16 CST 2020
     */
    List<TbClockworkTaskAndSlotRelation> selectByExample(TbClockworkTaskAndSlotRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_task_and_slot_relation
     *
     * @mbg.generated Wed Aug 05 09:46:16 CST 2020
     */
    TbClockworkTaskAndSlotRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_task_and_slot_relation
     *
     * @mbg.generated Wed Aug 05 09:46:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") TbClockworkTaskAndSlotRelation record, @Param("example") TbClockworkTaskAndSlotRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_task_and_slot_relation
     *
     * @mbg.generated Wed Aug 05 09:46:16 CST 2020
     */
    int updateByExample(@Param("record") TbClockworkTaskAndSlotRelation record, @Param("example") TbClockworkTaskAndSlotRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_task_and_slot_relation
     *
     * @mbg.generated Wed Aug 05 09:46:16 CST 2020
     */
    int updateByPrimaryKeySelective(TbClockworkTaskAndSlotRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_clockwork_task_and_slot_relation
     *
     * @mbg.generated Wed Aug 05 09:46:16 CST 2020
     */
    int updateByPrimaryKey(TbClockworkTaskAndSlotRelation record);
}