/**
 * This file is automatically generated by MyBatis Generator, do not modify.
 */
package com.creditease.adx.clockwork.dao.mapper.clockwork;

import com.creditease.adx.clockwork.common.entity.gen.TbClockworkRole;
import com.creditease.adx.clockwork.common.entity.gen.TbClockworkRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbClockworkRoleMapper {
    long countByExample(TbClockworkRoleExample example);

    int deleteByExample(TbClockworkRoleExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(TbClockworkRole record);

    int insertSelective(TbClockworkRole record);

    List<TbClockworkRole> selectByExample(TbClockworkRoleExample example);

    TbClockworkRole selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") TbClockworkRole record, @Param("example") TbClockworkRoleExample example);

    int updateByExample(@Param("record") TbClockworkRole record, @Param("example") TbClockworkRoleExample example);

    int updateByPrimaryKeySelective(TbClockworkRole record);

    int updateByPrimaryKey(TbClockworkRole record);
}