/**
 * This file is automatically generated by MyBatis Generator, do not modify.
 */
package com.creditease.adx.clockwork.dao.mapper.clockwork;

import com.creditease.adx.clockwork.common.entity.gen.TbClockworkDagRangeCheck;
import com.creditease.adx.clockwork.common.entity.gen.TbClockworkDagRangeCheckExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbClockworkDagRangeCheckMapper {
    long countByExample(TbClockworkDagRangeCheckExample example);

    int deleteByExample(TbClockworkDagRangeCheckExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(TbClockworkDagRangeCheck record);

    int insertSelective(TbClockworkDagRangeCheck record);

    List<TbClockworkDagRangeCheck> selectByExample(TbClockworkDagRangeCheckExample example);

    TbClockworkDagRangeCheck selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") TbClockworkDagRangeCheck record, @Param("example") TbClockworkDagRangeCheckExample example);

    int updateByExample(@Param("record") TbClockworkDagRangeCheck record, @Param("example") TbClockworkDagRangeCheckExample example);

    int updateByPrimaryKeySelective(TbClockworkDagRangeCheck record);

    int updateByPrimaryKey(TbClockworkDagRangeCheck record);

    int batchInsert(List<TbClockworkDagRangeCheck> records);
}