/**
 * This file is automatically generated by MyBatis Generator, do not modify.
 */

package com.creditease.adx.clockwork.common.pojo;

import com.creditease.adx.clockwork.common.entity.gen.TbClockworkTaskSubscription;
import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

/**
 * @ Author     ：XuanDongTang
 * @ Date       ：Created in 上午11:41 2020/12/12
 * @ Description：TbClockworkTaskSubscription
 * @ Modified By：
 */
public class TbClockworkTaskSubscriptionPojo extends TbClockworkTaskSubscription {


    @JsonFormat(pattern = "HH:mm:ss", timezone = "GMT+8")
    @Override
    public Date getSubscriptionTime() {
        return super.getSubscriptionTime();
    }

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    @Override
    public Date getCreateTime() {
        return super.getCreateTime();
    }

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    @Override
    public Date getUpdateTime() {
        return super.getUpdateTime();
    }


}
